import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ApolloWrapper from '@/lib/apollo-wrapper';
import { ThemeProvider, LayoutWrapper, InitialThemeScript } from '@/components/layout';
import { AuthProvider, I18nProvider } from '@/components/providers';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <InitialThemeScript />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider>
                    <AuthProvider>
                        <I18nProvider>
                            <ApolloWrapper>
                                <LayoutWrapper>
                                    {children}
                                </LayoutWrapper>
                            </ApolloWrapper>
                        </I18nProvider>
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
